tds_url: 'http://10.0.20.200:56788/get_sim?env=prod_db&quantity=1&reserved_by=TestAuto&sim_type=fake'
sim_reset_url: 'https://ecapi-staging.amaysim.net/ecgateway/_testing/bolt_testharness/boltharness.cfc?method=initialiseSim&sim='